apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: "tarasgroupki/k8s-auth:latest"
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: API_PORT
              valueFrom:
                configMapKeyRef:
                  name: global-configmap
                  key: API_PORT
            - name: AUTH_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: global-configmap
                  key: AUTH_SERVICE_HOST
            - name: PRODUCT_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: global-configmap
                  key: PRODUCT_SERVICE_HOST
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: global-configmap
                  key: POSTGRES_HOST
      imagePullSecrets:
        - name: dpr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - port: 3000
      targetPort: 3000
